// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package sqlc

import (
	"context"
)

const createAuthenticationData = `-- name: CreateAuthenticationData :one

INSERT INTO authenticationData(uuid, hashed_password, salt)
VALUES(?, ?, ?)
RETURNING uuid, hashed_password, salt
`

type CreateAuthenticationDataParams struct {
	Uuid           string
	HashedPassword string
	Salt           string
}

// -----------------------------------------------------------------------------
// CREATE QUERIES
func (q *Queries) CreateAuthenticationData(ctx context.Context, arg CreateAuthenticationDataParams) (AuthenticationDatum, error) {
	row := q.db.QueryRowContext(ctx, createAuthenticationData, arg.Uuid, arg.HashedPassword, arg.Salt)
	var i AuthenticationDatum
	err := row.Scan(&i.Uuid, &i.HashedPassword, &i.Salt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (uuid, username)
VALUES(?, ?)
RETURNING uuid, username
`

type CreateUserParams struct {
	Uuid     string
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Uuid, arg.Username)
	var i User
	err := row.Scan(&i.Uuid, &i.Username)
	return i, err
}

const deleteAuthData = `-- name: DeleteAuthData :exec

DELETE FROM authenticationData
WHERE uuid = ?
`

// -----------------------------------------------------------------------------
// DELETE QUERIES
func (q *Queries) DeleteAuthData(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthData, uuid)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE uuid = ?
`

func (q *Queries) DeleteUser(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, uuid)
	return err
}

const getAuthData = `-- name: GetAuthData :one

SELECT uuid, hashed_password, salt FROM authenticationData
WHERE uuid = ? 
LIMIT 1
`

// -----------------------------------------------------------------------------
// RETRIEVAL QUERIES
func (q *Queries) GetAuthData(ctx context.Context, uuid string) (AuthenticationDatum, error) {
	row := q.db.QueryRowContext(ctx, getAuthData, uuid)
	var i AuthenticationDatum
	err := row.Scan(&i.Uuid, &i.HashedPassword, &i.Salt)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT uuid, username FROM users
WHERE uuid = ? LIMIT 1
`

func (q *Queries) GetUserByUUID(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUID, uuid)
	var i User
	err := row.Scan(&i.Uuid, &i.Username)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT uuid, username FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.Uuid, &i.Username)
	return i, err
}

const updateAuthenticationData = `-- name: UpdateAuthenticationData :exec

UPDATE authenticationData
SET hashed_password = ?, salt = ?
WHERE uuid = ?
`

type UpdateAuthenticationDataParams struct {
	HashedPassword string
	Salt           string
	Uuid           string
}

// -----------------------------------------------------------------------------
// UPDATE QUERIES
func (q *Queries) UpdateAuthenticationData(ctx context.Context, arg UpdateAuthenticationDataParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthenticationData, arg.HashedPassword, arg.Salt, arg.Uuid)
	return err
}
