// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type AuthenticationDatum struct {
	Uuid           string
	Hashedpassword string
	Salt           string
}

type User struct {
	Uuid     string
	Username string
}
